export const constUsuario = {
    CADASTRO_NOME: 'CADASTRO_NOME',
    CADASTRO_CPF: 'CADASTRO_CPF',
    CADASTRO_EMAIL: 'CADASTRO_EMAIL',
    CADASTRO_SENHA: 'CADASTRO_SENHA',
    VALIDAR_SENHA: 'VALIDAR_SENHA',

    CADASTRAR_REQUEST: 'CADASTRAR_USUARIO_REQUEST',
    CADASTRAR_SUCCESSO: 'CADASTRAR_USUARIO_SUCCESSO',
    CADASTRAR_ERRO: 'CADASTRAR_USUARIO_ERRO',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESSO: 'LOGIN_SUCCESSO',
    LOGIN_ERRO: 'LOGIN_ERRO',
    
    LOGOUT: 'LOGOUT',  
};
