const USUARIO = {
    CADASTRAR_REQUEST: 'CADASTRAR_REQUEST',
    CADASTRAR_SUCESSO: 'CADASTRAR_SUCESSO',
    CADASTRAR_ERRO: 'CADASTRAR_ERRO',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCESSO: 'LOGIN_SUCESSO',
    LOGIN_ERRO: 'LOGIN_ERRO',
    
    LOGOUT: 'LOGOUT',  
};

export default USUARIO;